[package]
name = "post-me"
version = "0.1.0"
authors = ["Jakub Pastuszek <jpastuszek@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.2"
log = "0.4.8"
cotton = "0.0.6"
canteen = "0.5.2"
qrcode = "0.11.0"
nix = "0.15.0"
